import json
import random

# Major UN member states with their flag files
MAJOR_COUNTRIES = {
    'us': 'us_United_States.png',
    'cn': 'cn_China.png', 
    'ru': 'ru_Russia.png',
    'gb': 'gb_United_Kingdom.png',
    'fr': 'fr_France.png',
    'de': 'de_Germany.png',
    'jp': 'jp_Japan.png',
    'it': 'it_Italy.png',
    'ca': 'ca_Canada.png',
    'br': 'br_Brazil.png',
    'au': 'au_Australia.png',
    'in': 'in_India.png',
    'es': 'es_Spain.png',
    'mx': 'mx_Mexico.png',
    'kr': 'kr_South_Korea.png',
    'nl': 'nl_Netherlands.png',
    'sa': 'sa_Saudi_Arabia.png',
    'tr': 'tr_Turkey.png',
    'ch': 'ch_Switzerland.png',
    'se': 'se_Sweden.png',
    'pl': 'pl_Poland.png',
    'be': 'be_Belgium.png',
    'no': 'no_Norway.png',
    'at': 'at_Austria.png',
    'dk': 'dk_Denmark.png',
    'fi': 'fi_Finland.png',
    'ie': 'ie_Ireland.png',
    'pt': 'pt_Portugal.png',
    'gr': 'gr_Greece.png',
    'cz': 'cz_Czechia.png',
    'hu': 'hu_Hungary.png',
    'ro': 'ro_Romania.png',
    'bg': 'bg_Bulgaria.png',
    'hr': 'hr_Croatia.png',
    'sk': 'sk_Slovakia.png',
    'si': 'si_Slovenia.png',
    'lt': 'lt_Lithuania.png',
    'lv': 'lv_Latvia.png',
    'ee': 'ee_Estonia.png',
    'cy': 'cy_Cyprus.png',
    'mt': 'mt_Malta.png',
    'lu': 'lu_Luxembourg.png',
    'is': 'is_Iceland.png',
    'al': 'al_Albania.png',
    'mk': 'mk_North_Macedonia.png',
    'rs': 'rs_Serbia.png',
    'me': 'me_Montenegro.png',
    'ba': 'ba_Bosnia_and_Herzegovina.png',
    'ua': 'ua_Ukraine.png',
    'by': 'by_Belarus.png',
    'md': 'md_Moldova.png',
    'ge': 'ge_Georgia.png',
    'am': 'am_Armenia.png',
    'az': 'az_Azerbaijan.png',
    'kg': 'kg_Kyrgyzstan.png',
    'kz': 'kz_Kazakhstan.png',
    'uz': 'uz_Uzbekistan.png',
    'tj': 'tj_Tajikistan.png',
    'tm': 'tm_Turkmenistan.png',
    'af': 'af_Afghanistan.png',
    'pk': 'pk_Pakistan.png',
    'ir': 'ir_Iran.png',
    'iq': 'iq_Iraq.png',
    'sy': 'sy_Syria.png',
    'lb': 'lb_Lebanon.png',
    'jo': 'jo_Jordan.png',
    'il': 'il_Israel.png',
    'ps': 'ps_Palestine.png',
    'eg': 'eg_Egypt.png',
    'ly': 'ly_Libya.png',
    'tn': 'tn_Tunisia.png',
    'dz': 'dz_Algeria.png',
    'ma': 'ma_Morocco.png',
    'sd': 'sd_Sudan.png',
    'ss': 'ss_South_Sudan.png',
    'et': 'et_Ethiopia.png',
    'er': 'er_Eritrea.png',
    'dj': 'dj_Djibouti.png',
    'so': 'so_Somalia.png',
    'ke': 'ke_Kenya.png',
    'ug': 'ug_Uganda.png',
    'rw': 'rw_Rwanda.png',
    'bi': 'bi_Burundi.png',
    'tz': 'tz_Tanzania.png',
    'mw': 'mw_Malawi.png',
    'zm': 'zm_Zambia.png',
    'zw': 'zw_Zimbabwe.png',
    'bw': 'bw_Botswana.png',
    'na': 'na_Namibia.png',
    'za': 'za_South_Africa.png',
    'ls': 'ls_Lesotho.png',
    'sz': 'sz_Eswatini_(Swaziland).png',
    'mg': 'mg_Madagascar.png',
    'mu': 'mu_Mauritius.png',
    'sc': 'sc_Seychelles.png',
    'km': 'km_Comoros.png',
    'mz': 'mz_Mozambique.png',
    'ao': 'ao_Angola.png',
    'cg': 'cg_Republic_of_the_Congo.png',
    'cd': 'cd_DR_Congo.png',
    'ga': 'ga_Gabon.png',
    'cm': 'cm_Cameroon.png',
    'gq': 'gq_Equatorial_Guinea.png',
    'st': 'st_São_Tomé_and_Príncipe.png',
    'ng': 'ng_Nigeria.png',
    'ne': 'ne_Niger.png',
    'td': 'td_Chad.png',
    'cf': 'cf_Central_African_Republic.png',
    'ml': 'ml_Mali.png',
    'bf': 'bf_Burkina_Faso.png',
    'sn': 'sn_Senegal.png',
    'gm': 'gm_Gambia.png',
    'gw': 'gw_Guinea-Bissau.png',
    'gn': 'gn_Guinea.png',
    'sl': 'sl_Sierra_Leone.png',
    'lr': 'lr_Liberia.png',
    'ci': 'ci_Côte_d_Ivoire_(Ivory_Coast).png',
    'gh': 'gh_Ghana.png',
    'tg': 'tg_Togo.png',
    'bj': 'bj_Benin.png',
    'cv': 'cv_Cape_Verde.png',
    'mr': 'mr_Mauritania.png'
}

# Country names in Hungarian
COUNTRY_NAMES = {
    'us': 'Egyesült Államok',
    'cn': 'Kína',
    'ru': 'Oroszország',
    'gb': 'Egyesült Királyság',
    'fr': 'Franciaország',
    'de': 'Németország',
    'jp': 'Japán',
    'it': 'Olaszország',
    'ca': 'Kanada',
    'br': 'Brazília',
    'au': 'Ausztrália',
    'in': 'India',
    'es': 'Spanyolország',
    'mx': 'Mexikó',
    'kr': 'Dél-Korea',
    'nl': 'Hollandia',
    'sa': 'Szaúd-Arábia',
    'tr': 'Törökország',
    'ch': 'Svájc',
    'se': 'Svédország',
    'pl': 'Lengyelország',
    'be': 'Belgium',
    'no': 'Norvégia',
    'at': 'Ausztria',
    'dk': 'Dánia',
    'fi': 'Finnország',
    'ie': 'Írország',
    'pt': 'Portugália',
    'gr': 'Görögország',
    'cz': 'Csehország',
    'hu': 'Magyarország',
    'ro': 'Románia',
    'bg': 'Bulgária',
    'hr': 'Horvátország',
    'sk': 'Szlovákia',
    'si': 'Szlovénia',
    'lt': 'Litvánia',
    'lv': 'Lettország',
    'ee': 'Észtország',
    'cy': 'Ciprus',
    'mt': 'Málta',
    'lu': 'Luxemburg',
    'is': 'Izland',
    'al': 'Albánia',
    'mk': 'Észak-Macedónia',
    'rs': 'Szerbia',
    'me': 'Montenegró',
    'ba': 'Bosznia-Hercegovina',
    'ua': 'Ukrajna',
    'by': 'Fehéroroszország',
    'md': 'Moldova',
    'ge': 'Grúzia',
    'am': 'Örményország',
    'az': 'Azerbajdzsán',
    'kg': 'Kirgizisztán',
    'kz': 'Kazahsztán',
    'uz': 'Üzbegisztán',
    'tj': 'Tádzsikisztán',
    'tm': 'Türkmenisztán',
    'af': 'Afganisztán',
    'pk': 'Pakisztán',
    'ir': 'Irán',
    'iq': 'Irak',
    'sy': 'Szíria',
    'lb': 'Libanon',
    'jo': 'Jordánia',
    'il': 'Izrael',
    'ps': 'Palesztina',
    'eg': 'Egyiptom',
    'ly': 'Líbia',
    'tn': 'Tunézia',
    'dz': 'Algéria',
    'ma': 'Marokkó',
    'sd': 'Szudán',
    'ss': 'Dél-Szudán',
    'et': 'Etiópia',
    'er': 'Eritrea',
    'dj': 'Dzsibuti',
    'so': 'Szomália',
    'ke': 'Kenya',
    'ug': 'Uganda',
    'rw': 'Ruanda',
    'bi': 'Burundi',
    'tz': 'Tanzánia',
    'mw': 'Malawi',
    'zm': 'Zambia',
    'zw': 'Zimbabwe',
    'bw': 'Botswana',
    'na': 'Namíbia',
    'za': 'Dél-Afrika',
    'ls': 'Lesotho',
    'sz': 'Eswatini',
    'mg': 'Madagaszkár',
    'mu': 'Mauritius',
    'sc': 'Seychelle-szigetek',
    'km': 'Comore-szigetek',
    'mz': 'Mozambik',
    'ao': 'Angola',
    'cg': 'Kongói Köztársaság',
    'cd': 'Kongói Demokratikus Köztársaság',
    'ga': 'Gabon',
    'cm': 'Kamerun',
    'gq': 'Egyenlítői-Guinea',
    'st': 'São Tomé és Príncipe',
    'ng': 'Nigéria',
    'ne': 'Niger',
    'td': 'Csád',
    'cf': 'Közép-afrikai Köztársaság',
    'ml': 'Mali',
    'bf': 'Burkina Faso',
    'sn': 'Szenegál',
    'gm': 'Gambia',
    'gw': 'Bissau-Guinea',
    'gn': 'Guinea',
    'sl': 'Sierra Leone',
    'lr': 'Libéria',
    'ci': 'Elefántcsontpart',
    'gh': 'Ghána',
    'tg': 'Togo',
    'bj': 'Benin',
    'cv': 'Zöld-foki Köztársaság',
    'mr': 'Mauritánia'
}

# Generate questions
questions = []
country_codes = list(MAJOR_COUNTRIES.keys())

for code in country_codes:
    if code in COUNTRY_NAMES:
        country_name = COUNTRY_NAMES[code]
        flag_file = f"../world_flags_project/data/flags/{MAJOR_COUNTRIES[code]}"
        
        # Pick 3 random other countries
        other_codes = [c for c in country_codes if c != code]
        other_names = [COUNTRY_NAMES[c] for c in random.sample(other_codes, 3)]
        options = other_names + [country_name]
        random.shuffle(options)
        correct = options.index(country_name)
        
        questions.append({
            'question': 'Ez a zászló melyik országhoz tartozik?',
            'logo_path': flag_file,
            'options': options,
            'correct': correct,
            'explanation': f"Ez {country_name} zászlaja."
        })

# Write to file
with open('topics/zaszlok_all_questions.py', 'w', encoding='utf-8') as f:
    f.write('# AUTO-GENERATED: Fő ENSZ-tagországok zászlói\n')
    f.write('ZASZLOK_QUESTIONS_ALL = [\n')
    for q in questions:
        f.write('    ' + repr(q) + ',\n')
    f.write(']\n')

print(f"Generated {len(questions)} flag questions.")
print("File created: topics/zaszlok_all_questions.py") 